repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-aws-credentials
      - id: detect-private-key
  - repo: https://github.com/trailofbits/pre-commit-hooks
    rev: v0.15.0
    hooks:
      - id: trufflehog
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.59.0
    hooks:
      - id: eslint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.10.0
    hooks:
      - id: prettier
